-- Plugin Configurations
require("core.plugin_config.lualine")
require("core.plugin_config.comment")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.gitsigns")
require("core.plugin_config.telescope")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.neodev")
require("core.plugin_config.cmp")
require("core.plugin_config.null-ls")
require("core.plugin_config.rose-pine")
require("core.plugin_config.tokyonight")
require("core.plugin_config.nvim-ts-autotag")
require("core.plugin_config.nvim-autopairs")
-- require("core.plugin_config.tabout")
-- require("core.plugin_config.enfocado")
require("core.plugin_config.todo-comments")
require("core.plugin_config.bluloco")
require("core.plugin_config.alpha")
require("core.plugin_config.toggleterm")
require("core.plugin_config.cheatsheet")
require("core.plugin_config.noice")
require("core.plugin_config.inc_rename")
