-- TODO: add seach etc.
-- FIX: https://github.com/mg979/vim-visual-multi
-- TODO: https://github.com/stevearc/dressing.nvim for refactor
-- TODO: configure legend.lua
-- TODO: https://github.com/gcmt/wildfire.vim
